default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: <%= ENV['DATABASE_USERNAME'] %> 
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['SOCKET'] %>

development:
  <<: *default
  database: angipl_udemy_development

test:
  <<: *default
  database: angipl_udemy_test
