default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: <%= ENV['DATABASE_USERNAME'] %> 
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['SOCKET'] %>

development:
  <<: *default
  database: idioms_game_development

test:
  <<: *default
  database: idioms_game_test

production:
  adapter:  postgresql
  encoding: unicode
  pool:     5
  host:     <%= ENV['POSTGRESQL_HOST'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  username: <%= ENV['POSTGRESQL_USER_NAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  